version: '3.1'

services:
  app:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    command: sh -c "yarn && yarn start"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tweetulator_db
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
